"""advanced analytics tables

Revision ID: bf39e54dce0b
Revises: 202dc13bca11
Create Date: 2026-09-28 21:44:13.521093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf39e54dce0b'
down_revision: Union[str, None] = '202dc13bca11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineup_stats',
    sa.Column('group_id', sa.String(length=120), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=7), nullable=False),
    sa.Column('season_type', sa.String(length=20), nullable=False),
    sa.Column('group_quantity', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=300), nullable=True),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('off_rating', sa.Float(), nullable=True),
    sa.Column('def_rating', sa.Float(), nullable=True),
    sa.Column('net_rating', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('group_id', 'team_id', 'season', 'season_type', 'group_quantity')
    )
    op.create_table('shots',
    sa.Column('game_id', sa.String(length=10), nullable=False),
    sa.Column('game_event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=7), nullable=False),
    sa.Column('season_type', sa.String(length=20), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=True),
    sa.Column('shot_type', sa.String(length=30), nullable=True),
    sa.Column('zone_basic', sa.String(length=40), nullable=True),
    sa.Column('zone_area', sa.String(length=40), nullable=True),
    sa.Column('zone_range', sa.String(length=40), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('loc_x', sa.Integer(), nullable=True),
    sa.Column('loc_y', sa.Integer(), nullable=True),
    sa.Column('made', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('game_id', 'game_event_id', 'player_id')
    )
    op.create_index('ix_shots_player_season', 'shots', ['player_id', 'season'], unique=False)
    op.create_table('player_season_advanced',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=7), nullable=False),
    sa.Column('season_type', sa.String(length=20), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('mpg', sa.Float(), nullable=True),
    sa.Column('ts_pct', sa.Float(), nullable=True),
    sa.Column('efg_pct', sa.Float(), nullable=True),
    sa.Column('usg_pct', sa.Float(), nullable=True),
    sa.Column('ast_pct', sa.Float(), nullable=True),
    sa.Column('reb_pct', sa.Float(), nullable=True),
    sa.Column('tov_pct', sa.Float(), nullable=True),
    sa.Column('game_score', sa.Float(), nullable=True),
    sa.Column('pts_per36', sa.Float(), nullable=True),
    sa.Column('reb_per36', sa.Float(), nullable=True),
    sa.Column('ast_per36', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season', 'season_type')
    )
    op.create_table('team_season_advanced',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=7), nullable=False),
    sa.Column('season_type', sa.String(length=20), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('off_rtg', sa.Float(), nullable=True),
    sa.Column('def_rtg', sa.Float(), nullable=True),
    sa.Column('net_rtg', sa.Float(), nullable=True),
    sa.Column('efg_pct', sa.Float(), nullable=True),
    sa.Column('tov_pct', sa.Float(), nullable=True),
    sa.Column('orb_pct', sa.Float(), nullable=True),
    sa.Column('ft_rate', sa.Float(), nullable=True),
    sa.Column('opp_efg_pct', sa.Float(), nullable=True),
    sa.Column('opp_tov_pct', sa.Float(), nullable=True),
    sa.Column('drb_pct', sa.Float(), nullable=True),
    sa.Column('opp_ft_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'season', 'season_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_season_advanced')
    op.drop_table('player_season_advanced')
    op.drop_index('ix_shots_player_season', table_name='shots')
    op.drop_table('shots')
    op.drop_table('lineup_stats')
    # ### end Alembic commands ###
